export const ActionTypes = {
  RECEIVE_DASHBOARDS: 'RECEIVE_DASHBOARDS',
  RECEIVE_DASHBOARD: 'RECEIVE_DASHBOARD',

  ADD_CHART_TO_DASHBOARD: 'ADD_CHART_TO_DASHBOARD',
  ADD_CHART_TO_DASHBOARD_PENDING: 'ADD_CHART_TO_DASHBOARD_PENDING',
  ADD_CHART_TO_DASHBOARD_SUCCESS: 'ADD_CHART_TO_DASHBOARD_SUCCESS',
  ADD_CHART_TO_DASHBOARD_FAILED: 'ADD_CHART_TO_DASHBOARD_FAILED',

  FETCH_HYDRATED_DASHBOARD: 'FETCH_HYDRATED_DASHBOARD',
  FETCH_HYDRATED_DASHBOARD_PENDING: 'FETCH_HYDRATED_DASHBOARD_PENDING',
  FETCH_HYDRATED_DASHBOARD_SUCCESS: 'FETCH_HYDRATED_DASHBOARD_SUCCESS',
  FETCH_HYDRATED_DASHBOARD_FAILED: 'FETCH_HYDRATED_DASHBOARD_FAILED',

  REMOVE_CHART_FROM_DASHBOARD: 'REMOVE_CHART_FROM_DASHBOARD',
  REMOVE_CHART_FROM_DASHBOARD_PENDING: 'REMOVE_CHART_FROM_DASHBOARD_PENDING',
  REMOVE_CHART_FROM_DASHBOARD_SUCCESS: 'REMOVE_CHART_FROM_DASHBOARD_SUCCESS',
  REMOVE_CHART_FROM_DASHBOARD_FAILED: 'REMOVE_CHART_FROM_DASHBOARD_FAILED',
};
