export const ActionTypes = {
  SET_TOKEN: 'SET_TOKEN',
  SET_ME: 'SET_ME',

  VERIFY_USER: 'VERIFY_USER',
  VERIFY_USER_PENDING: 'VERIFY_USER_PENDING',
  VERIFY_USER_SUCCESS: 'VERIFY_USER_SUCCESS',
  VERIFY_USER_FAILED: 'VERIFY_USER_FAILED',

  REPORT_FALSE_EMAIL: 'REPORT_FALSE_EMAIL',
  REPORT_FALSE_EMAIL_PENDING: 'REPORT_FALSE_EMAIL_PENDING',
  REPORT_FALSE_EMAIL_SUCCESS: 'REPORT_FALSE_EMAIL_SUCCESS',
  REPORT_FALSE_EMAIL_FAILED: 'REPORT_FALSE_EMAIL_FAILED',
};
