export const ActionTypes = {
  RECEIVE_END_USERS_PAGE: 'RECEIVE_END_USERS_PAGE',

  FETCH_END_USER_EVENTS: 'FETCH_END_USER_EVENTS',
  FETCH_END_USER_EVENTS_PENDING: 'FETCH_END_USER_EVENTS_PENDING',
  FETCH_END_USER_EVENTS_SUCCESS: 'FETCH_END_USER_EVENTS_SUCCESS',
  FETCH_END_USER_EVENTS_FAILED: 'FETCH_END_USER_EVENTS_FAILED',

  HANDLE_SET_FILTER: 'HANDLE_SET_FILTER',
};
