export const ActionTypes = {
  FETCH_NAME_TYPEAHEAD: 'FETCH_NAME_TYPEAHEAD',
  FETCH_NAME_TYPEAHEAD_PENDING: 'FETCH_NAME_TYPEAHEAD_PENDING',
  FETCH_NAME_TYPEAHEAD_FAILED: 'FETCH_NAME_TYPEAHEAD_FAILED',
  FETCH_NAME_TYPEAHEAD_SUCCESS: 'FETCH_NAME_TYPEAHEAD_SUCCESS',

  FETCH_EVENT_SERIES: 'FETCH_EVENT_SERIES',
  FETCH_EVENT_SERIES_PENDING: 'FETCH_EVENT_SERIES_PENDING',
  FETCH_EVENT_SERIES_FAILED: 'FETCH_EVENT_SERIES_FAILED',
  FETCH_EVENT_SERIES_SUCCESS: 'FETCH_EVENT_SERIES_SUCCESS',
};
