export const ActionTypes = {
  FETCH_NAME_TYPEAHEAD: 'FETCH_NAME_TYPEAHEAD',
  FETCH_NAME_TYPEAHEAD_PENDING: 'FETCH_NAME_TYPEAHEAD_PENDING',
  FETCH_NAME_TYPEAHEAD_FAILED: 'FETCH_NAME_TYPEAHEAD_FAILED',
  FETCH_NAME_TYPEAHEAD_SUCCESS: 'FETCH_NAME_TYPEAHEAD_SUCCESS',
};
