const prefixes = [
  'Adamant',
  'Adroit',
  'Amatory',
  'Animistic',
  'Antic',
  'Arcadian',
  'Baleful',
  'Bellicose',
  'Bilious',
  'Boorish',
  'Calamitous',
  'Caustic',
  'Cerulean',
  'Comely',
  'Concomitant',
  'Contumacious',
  'Corpulent',
  'Crapulous',
  'Defamatory',
  'Didactic',
  'Dilatory',
  'Dowdy',
  'Efficacious',
  'Effulgent',
  'Egregious',
  'Endemic',
  'Equanimous',
  'Execrable',
  'Fastidious',
  'Feckless',
  'Fecund',
  'Friable',
  'Fulsome',
  'Garrulous',
  'Guileless',
  'Gustatory',
  'Heuristic',
  'Histrionic',
  'Hubristic',
  'Incendiary',
  'Insidious',
  'Insolent',
  'Intransigent',
  'Inveterate',
  'Invidious',
  'Irksome',
  'Jejune',
  'Jocular',
  'Judicious',
  'Lachrymose',
  'Limpid',
  'Loquacious',
  'Luminous',
  'Mannered',
  'Mendacious',
  'Meretricious',
  'Minatory',
  'Mordant',
  'Munificent',
  'Nefarious',
  'Noxious',
  'Obtuse',
  'Parsimonious',
  'Pendulous',
  'Pernicious',
  'Pervasive',
  'Petulant',
  'Platitudinous',
  'Precipitate',
  'Propitious',
  'Puckish',
  'Querulous',
  'Quiescent',
  'Rebarbative',
  'Recalcitrant',
  'Redolent',
  'Rhadamanthine',
  'Risible',
  'Ruminative',
  'Sagacious',
  'Salubrious',
  'Sartorial',
  'Sclerotic',
  'Serpentine',
  'Spasmodic',
  'Strident',
  'Taciturn',
  'Tenacious',
  'Tremulous',
  'Trenchant',
  'Turbulent',
  'Turgid',
  'Ubiquitous',
  'Uxorious',
  'Verdant',
  'Voluble',
  'Voracious',
  'Wheedling',
  'Withering',
  'Zealous',
];

const suffixes = [
  "Acantharea","Anemone","Angelfish King","Ahi Tuna","Albacore","American Oyster","Anchovy","Armored Snail","Arctic Char","Atlantic Bluefin Tuna","Atlantic Cod","Atlantic Goliath Grouper","Atlantic Trumpetfish","Atlantic Wolffish","Baleen Whale","Banded Butterflyfish","Banded Coral Shrimp","Banded Sea Krait","Barnacle","Barndoor Skate","Barracuda","Basking Shark","Bass","Beluga Whale","Bluebanded Goby","Bluehead Wrasse","Bluefish","Bluestreak Cleaner-Wrasse","Blue Marlin","Blue Shark","Blue Spiny Lobster","Blue Tang","Blue Whale","Broadclub Cuttlefish","Bull Shark","Chambered Nautilus","Chilean Basket Star","Chilean Jack Mackerel","Chinook Salmon","Christmas Tree Worm","Clam","Clown Anemonefish","Clown Triggerfish","Cod","Coelacanth","Cockscomb Cup Coral","Common Fangtooth","Conch","Cookiecutter Shark","Copepod","Coral","Corydoras","Cownose Ray","Crab","Crown-of-Thorns Starfish","Cushion Star","Cuttlefish","California Sea Otters","Dolphin","Dolphinfish","Dory","Devil Fish","Dugong","Dumbo Octopus","Dungeness Crab","Eccentric Sand Dollar","Edible Sea Cucumber","Eel","Elephant Seal","Elkhorn Coral","Emperor Shrimp","Estuarine Crocodile","Fathead Sculpin","Fiddler Crab","Fin Whale","Flameback","Flamingo Tongue Snail","Flashlight Fish","Flatback Turtle","Flatfish","Flying Fish","Flounder","Fluke","French Angelfish","Frilled Shark","Fugu (also called Pufferfish)","Gar","Geoduck","Giant Barrel Sponge","Giant Caribbean Sea Anemone","Giant Clam","Giant Isopod","Giant Kingfish","Giant Oarfish","Giant Pacific Octopus","Giant Pyrosome","Giant Sea Star","Giant Squid","Glowing Sucker Octopus","Giant Tube Worm","Goblin Shark","Goosefish","Great White Shark","Greenland Shark","Grey Atlantic Seal","Grouper","Grunion","Guineafowl Puffer","Haddock","Hake","Halibut","Hammerhead Shark","Hapuka","Harbor Porpoise","Harbor Seal","Hatchetfish","Hawaiian Monk Seal","Hawksbill Turtle","Hector's Dolphin","Hermit Crab","Herring","Hoki","Horn Shark","Horseshoe Crab","Humpback Anglerfish","Humpback Whale","Icefish","Imperator Angelfish","Irukandji Jellyfish","Isopod","Ivory Bush Coral","Japanese Spider Crab","Jellyfish","John Dory","Juan Fernandez Fur Seal","Killer Whale","Kiwa Hirsuta","Krill","Lagoon Triggerfish","Lamprey","Leafy Seadragon","Leopard Seal","Limpet","Ling","Lionfish","Lions Mane Jellyfish","Lobe Coral","Lobster","Loggerhead Turtle","Longnose Sawshark","Longsnout Seahorse","Lophelia Coral","Marrus Orthocanna","Manatee","Manta Ray","Marlin","Megamouth Shark","Mexican Lookdown","Mimic Octopus","Moon Jelly","Mollusk","Monkfish","Moray Eel","Mullet","Mussel","Megaladon","Napoleon Wrasse","Nassau Grouper","Narwhal","Nautilus","Needlefish","Northern Seahorse","North Atlantic Right Whale","Northern Red Snapper","Norway Lobster","Nudibranch","Nurse Shark","Oarfish","Ocean Sunfish","Oceanic Whitetip Shark","Octopus","Olive Sea Snake","Orange Roughy","Ostracod","Otter","Oyster","Pacific Angelshark","Pacific Blackdragon","Pacific Halibut","Pacific Sardine","Pacific Sea Nettle Jellyfish","Pacific White Sided Dolphin","Pantropical Spotted Dolphin","Patagonian Toothfish","Peacock Mantis Shrimp","Pelagic Thresher Shark","Penguin","Peruvian Anchoveta","Pilchard","Pink Salmon","Pinniped","Plankton","Porpoise","Polar Bear","Portuguese Man o' War","Pycnogonid Sea Spider","Quahog","Queen Angelfish","Queen Conch","Queen Parrotfish","Queensland Grouper","Ragfish","Ratfish","Rattail Fish","Ray","Red Drum","Red King Crab","Ringed Seal","Risso's Dolphin","Ross Seals","Sablefish","Salmon","Sand Dollar","Sandbar Shark","Sawfish","Sarcastic Fringehead","Scalloped Hammerhead Shark","Seahorse","Sea Cucumber","Sea Lion","Sea Urchin","Seal","Shark","Shortfin Mako Shark","Shovelnose Guitarfish","Shrimp","Silverside Fish","Skipjack Tuna","Slender Snipe Eel","Smalltooth Sawfish","Smelts","Sockeye Salmon","Southern Stingray","Sponge","Spotted Porcupinefish","Spotted Dolphin","Spotted Eagle Ray","Spotted Moray","Squid","Squidworm","Starfish","Stickleback","Stonefish","Stoplight Loosejaw","Sturgeon","Swordfish","Tan Bristlemouth","Tasseled Wobbegong","Terrible Claw Lobster","Threespot Damselfish","Tiger Prawn","Tiger Shark","Tilefish","Toadfish","Tropical Two-Wing Flyfish","Tuna","Umbrella Squid","Velvet Crab","Venus Flytrap Sea Anemone","Vigtorniella Worm","Viperfish","Vampire Squid","Vaquita","Wahoo","Walrus","West Indian Manatee","Whale","Whale Shark","Whiptail Gulper","White-Beaked Dolphin","White-Ring Garden Eel","White Shrimp","Wobbegong","Wrasse","Wreckfish","Xiphosura","Yellowtail Damselfish","Yelloweye Rockfish","Yellow Cup Black Coral","Yellow Tube Sponge","Yellowfin Tuna","Zebrashark","Zooplankton",
  "Aardwolf","Addax","African Wild Ass","Ant","Antelope","Armadillo","Baboon","Badger","Bat","Bearded Dragon","Beetle","Bird","Black-footed Cat","Boa","Brown Bear","Bustard","Butterfly","Camel","Caracal","Caracara","Caterpillar","Centipede","Cheetah","Chipmunk","Chuckwalla","Climbing Mouse","Coati","Cobra","Cotton Rat","Cougar","Courser","Crane Fly","Crow","Dassie Rat","Dove","Dunnart","Eagle","Echidna","Elephant","Emu","Falcon","Fly","Fox","Frogmouth","Gecko","Geoffroy's Cat","Gerbil","Grasshopper","Guanaco","Gundi","Hamster","Hawk","Hedgehog","Hyena","Hyrax","Jackal","Kangaroo","Kangaroo Rat","Kestrel","Kowari","Kultarr","Leopard","Lion","Macaw","Meerkat","Mouse","Oryx","Ostrich","Owl","Pronghorn","Python","Rabbit","Raccoon","Rattlesnake","Rhinoceros","Sand Cat","Spectacled Bear","Spiny Mouse","Starling","Stick Bug","Tarantula","Tit","Toad","Tortoise","Tyrant Flycatcher","Viper","Vulture","Waxwing","Xerus","Zebra",
  "Aardvark","Aardwolf","Accentor","African Buffalo","African Wild Dog","Alpaca","Anaconda","Ant","Anteater","Antelope","Armadillo","Baboon","Badger","Bandicoot","Barbet","Bat","Bee","Bee-eater","Beetle","Bird","Bison","Black-footed Cat","Black-footed Ferret","Bluebird","Boa","Bowerbird","Brown Bear","Bush Dog","Bushshrike","Bustard","Butterfly","Buzzard","Caracal","Caracara","Cardinal","Caterpillar","Cheetah","Chipmunk","Civet","Climbing Mouse","Clouded Leopard","Coati","Cobra","Cockatoo","Cockroach","Common Genet","Cotton Rat","Cougar","Courser","Coyote","Crane","Crane Fly","Cricket","Crow","Culpeo","Death Adder","Deer","Deer Mouse","Dingo","Dinosaur","Dove","Drongo","Duck","Duiker","Dunnart","Eagle","Echidna","Elephant","Elk","Emu","Falcon","Finch","Flea","Fly","Flying Frog","Fox","Frog","Frogmouth","Garter Snake","Gazelle","Gecko","Geoffroy's Cat","Gerbil","Giant Tortoise","Giraffe","Grasshopper","Grison","Groundhog","Grouse","Guanaco","Guinea Pig","Hamster","Harrier","Hartebeest","Hawk","Hedgehog","Helmetshrike","Hippopotamus","Hornbill","Hyena","Hyrax","Impala","Jackal","Jaguar","Jaguarundi","Kangaroo","Kangaroo Rat","Kestrel","Kultarr","Ladybug","Leopard","Lion","Macaw","Meerkat","Mouse","Newt","Oryx","Ostrich","Owl","Pangolin","Pheasant","Prairie Dog","Pronghorn","Przewalski's Horse","Python","Quoll","Rabbit","Raven","Rhinoceros","Shelduck","Sloth Bear","Spectacled Bear","Squirrel","Starling","Stick Bug","Tamandua","Tasmanian Devil","Thornbill","Thrush","Toad","Tortoise",
  "Agouti","Anaconda","Anoa","Ant","Anteater","Antelope","Armadillo","Asian Black Bear","Aye-aye","Babirusa","Baboon","Badger","Bandicoot","Banteng","Barbet","Basilisk","Bat","Bearded Dragon","Bee","Bee-eater","Beetle","Bettong","Binturong","Bird-of-paradise","Bongo","Bowerbird","Bulbul","Bush Dog","Bushbaby","Bushshrike","Butterfly","Buzzard","Caecilian","Cardinal","Cassowary","Caterpillar","Centipede","Chameleon","Chimpanzee","Cicada","Civet","Clouded Leopard","Coati","Cobra","Cockatoo","Cockroach","Colugo","Cotinga","Cotton Rat","Cougar","Crane Fly","Cricket","Crocodile","Crow","Cuckoo","Cuscus","Death Adder","Deer","Dhole","Dingo","Dinosaur","Drongo","Duck","Duiker","Eagle","Echidna","Elephant","Finch","Flat-headed Cat","Flea","Flowerpecker","Fly","Flying Frog","Fossa","Frog","Frogmouth","Gaur","Gecko","Gorilla","Grison","Hawaiian Honeycreeper","Hawk","Hedgehog","Helmetshrike","Hornbill","Hyrax","Iguana","Jackal","Jaguar","Jaguarundi","Kestrel","Ladybug","Lemur","Leopard","Lion","Macaw","Mandrill","Margay","Monkey","Mouse","Mouse Deer","Newt","Okapi","Old World Flycatcher","Orangutan","Owl","Pangolin","Peafowl","Pheasant","Possum","Python","Quokka","Rabbit","Raccoon","Red Panda","Red River Hog","Rhinoceros","Sloth Bear","Spectacled Bear","Squirrel","Starling","Stick Bug","Sun Bear","Tamandua","Tamarin","Tapir","Tarantula","Thrush","Tiger","Tit","Toad","Tortoise","Toucan","Trogon","Trumpeter","Turaco","Turtle","Tyrant Flycatcher","Viper","Vulture","Wallaby","Warbler","Wasp","Waxwing","Weaver","Weaver-finch","Whistler","White-eye","Whydah","Woodswallow","Worm","Wren","Xenops","Yellowjacket","Accentor","African Buffalo","American Black Bear","Anole","Bird","Bison","Boa","Brown Bear","Chipmunk","Common Genet","Copperhead","Coyote","Deer Mouse","Dormouse","Elk","Emu","Fisher","Fox","Garter Snake","Giant Panda","Giant Tortoise","Groundhog","Grouse","Guanaco","Himalayan Tahr","Kangaroo","Koala","Numbat","Quoll","Raccoon dog","Tasmanian Devil","Thornbill","Turkey","Vole","Weasel","Wildcat","Wolf","Wombat","Woodchuck","Woodpecker",
  "Alpaca","Buffalo","Banteng","Cow","Cat","Chicken","Carp","Camel","Donkey","Dog","Duck","Emu","Goat","Gayal","Guinea","Goose","Horse","Honey","Llama","Pig","Pigeon","Rhea","Rabbit","Sheep","Silkworm","Turkey","Yak","Zebu",
  "Bearded Dragon","Birds","Burro","Cats","Chameleons","Chickens","Chinchillas","Chinese Water Dragon","Cows","Dogs","Donkey","Ducks","Ferrets","Fish","Geckos","Geese","Gerbils","Goats","Guinea Fowl","Guinea Pigs","Hamsters","Hedgehogs","Horses","Iguanas","Llamas","Lizards","Mice","Mule","Peafowl","Pigs and Hogs","Pigeons","Ponies","Pot Bellied Pig","Rabbits","Rats","Sheep","Skinks","Snakes","Stick Insects","Sugar Gliders","Tarantula","Turkeys","Turtles",
  "Aardvark","African Wild Dog","Aldabra Tortoise","American Alligator","American Bison","Amur Tiger","Anaconda","Andean Condor","Asian Elephant","Baby Doll Sheep","Bald Eagle","Barred Owl","Blue Iguana","Boer Goat","California Sea Lion","Caribbean Flamingo","Chinchilla","Collared Lemur","Coquerel's Sifaka","Cuban Amazon Parrot","Ebony Langur","Fennec Fox","Fossa","Gelada","Giant Anteater","Giraffe","Gorilla","Grizzly Bear","Henkel's Leaf-tailed Gecko","Indian Gharial","Indian Rhinoceros","King Cobra","King Vulture","Komodo Dragon","Linne's Two-toed Sloth","Lion","Little Penguin","Madagascar Tree Boa","Magellanic Penguin","Malayan Tapir","Malayan Tiger","Matschies Tree Kangaroo","Mini Donkey","Monarch Butterfly","Nile crocodile","North American Porcupine","Nubian Ibex","Okapi","Poison Dart Frog","Polar Bear","Pygmy Marmoset","Radiated Tortoise","Red Panda","Red Ruffed Lemur","Ring-tailed Lemur","Ring-tailed Mongoose","Rock Hyrax","Small Clawed Asian Otter","Snow Leopard","Snowy Owl","Southern White-faced Owl","Southern White Rhinocerous","Squirrel Monkey","Tufted Puffin","White Cheeked Gibbon","White-throated Bee Eater","Zebra",
  "Airline Pilot",
  "Academic Team",
  "Accountant",
  "Account Executive",
  "Actor",
  "Actuary",
  "Acquisition Analyst",
  "Administrative Asst.",
  "Administrative Analyst",
  "Administrator",
  "Advertising Director",
  "Aerospace Engineer",
  "Agent",
  "Agricultural Inspector",
  "Agricultural Scientist",
  "Air Traffic Controller",
  "Animal Trainer",
  "Anthropologist",
  "Appraiser",
  "Architect",
  "Art Director",
  "Artist",
  "Astronomer",
  "Athletic Coach",
  "Auditor",
  "Author",
  "Baker",
  "Banker",
  "Bankruptcy Attorney",
  "Benefits Manager",
  "Biologist",
  "Bio-feedback Specialist",
  "Biomedical Engineer",
  "Biotechnical Researcher",
  "Broadcaster",
  "Broker",
  "Building Manager",
  "Building Contractor",
  "Building Inspector",
  "Business Analyst",
  "Business Planner",
  "Business Manager",
  "Buyer",
  "Call Center Manager",
  "Career Counselor",
  "Cash Manager",
  "Ceramic Engineer",
  "Chief Executive Officer",
  "Chief Operation Officer",
  "Chef",
  "Chemical Engineer",
  "Chemist",
  "Child Care Manager",
  "Chief Medical Officer",
  "Chiropractor",
  "Cinematographer",
  "City Housing Manager",
  "City Manager",
  "Civil Engineer",
  "Claims Manager",
  "Clinical Research Assistant",
  "Collections Manager.",
  "Compliance Manager",
  "Comptroller",
  "Computer Manager",
  "Commercial Artist",
  "Communications Affairs Director",
  "Communications Director",
  "Communications Engineer",
  "Compensation Analyst",
  "Computer Programmer",
  "Computer Ops. Manager",
  "Computer Engineer",
  "Computer Operator",
  "Computer Graphics Specialist",
  "Construction Engineer",
  "Construction Manager",
  "Consultant",
  "Consumer Relations Manager",
  "Contract Administrator",
  "Copyright Attorney",
  "Copywriter",
  "Corporate Planner",
  "Corrections Officer",
  "Cosmetologist",
  "Credit Analyst",
  "Cruise Director",
  "Chief Information Officer",
  "Chief Technology Officer",
  "Customer Service Manager",
  "Cryptologist",
  "Dancer",
  "Data Security Manager",
  "Database Manager",
  "Day Care Instructor",
  "Dentist",
  "Designer",
  "Design Engineer",
  "Desktop Publisher",
  "Developer",
  "Development Officer",
  "Diamond Merchant",
  "Dietitian",
  "Direct Marketer",
  "Director",
  "Distribution Manager",
  "Diversity Manager",
  "Economist",
  "EEO Compliance Manager",
  "Editor",
  "Education Adminator",
  "Electrical Engineer",
  "Electro Optical Engineer",
  "Electronics Engineer",
  "Embassy Management",
  "Employment Agent",
  "Engineer Technician",
  "Entrepreneur",
  "Environmental Analyst",
  "Environmental Attorney",
  "Environmental Engineer",
  "Environmental Specialist",
  "Escrow Officer",
  "Estimator",
  "Executive Assistant",
  "Executive Director",
  "Executive Recruiter",
  "Facilities Manager",
  "Family Counselor",
  "Fashion Events Manager",
  "Fashion Merchandiser",
  "Fast Food Manager",
  "Film Producer",
  "Film Production Assistant",
  "Financial Analyst",
  "Financial Planner",
  "Financier",
  "Fine Artist",
  "Wildlife Specialist",
  "Fitness Consultant",
  "Flight Attendant",
  "Flight Engineer",
  "Floral Designer",
  "Food & Beverage Director",
  "Food Service Manager",
  "Forestry Technician",
  "Franchise Management",
  "Franchise Sales",
  "Fraud Investigator",
  "Freelance Writer",
  "Fund Raiser",
  "General Manager",
  "Geologist",
  "General Counsel",
  "Geriatric Specialist",
  "Gerontologist",
  "Glamour Photographer",
  "Golf Club Manager",
  "Gourmet Chef",
  "Graphic Designer",
  "Grounds Keeper",
  "Hazardous Waste Manager",
  "Health Care Manager",
  "Health Therapist",
  "Health Service Administrator",
  "Hearing Officer",
  "Home Economist",
  "Horticulturist",
  "Hospital Administrator",
  "Hotel Manager",
  "Human Resources Manager",
  "Importer",
  "Industrial Designer",
  "Industrial Engineer",
  "Information Director",
  "Inside Sales",
  "Insurance Adjuster",
  "Interior Decorator",
  "Internal Controls Director",
  "International Acct.",
  "International Courier",
  "International Lawyer",
  "Interpreter",
  "Investigator",
  "Investment Banker",
  "Investment Manager",
  "IT Architect",
  "IT Project Manager",
  "IT Systems Analyst",
  "Jeweler",
  "Joint Venture Manager",
  "Journalist",
  "Labor Negotiator",
  "Labor Organizer",
  "Labor Relations Manager",
  "Lab Services Director",
  "Lab Technician",
  "Land Developer",
  "Landscape Architect",
  "Law Enforcement Officer",
  "Lawyer",
  "Lead Software Engineer",
  "Lead Software Test Engineer",
  "Leasing Manager",
  "Legal Secretary",
  "Library Manager",
  "Litigation Attorney",
  "Loan Officer",
  "Lobbyist",
  "Logistics Manager",
  "Maintenance Manager",
  "Management Consultant",
  "Managed Care Director",
  "Managing Partner",
  "Manufacturing Director",
  "Manpower Planner",
  "Marine Biologist",
  "Market Res. Analyst",
  "Marketing Director",
  "Materials Manager",
  "Mathematician",
  "Membership Chairman",
  "Mechanic",
  "Mechanical Engineer",
  "Media Buyer",
  "Medical Investor",
  "Medical Secretary",
  "Medical Technician",
  "Mental Health Counselor",
  "Merchandiser",
  "Metallurgical Engineering",
  "Meteorologist",
  "Microbiologist",
  "MIS Manager",
  "Motion Picture Director",
  "Multimedia Director",
  "Musician",
  "Network Administrator",
  "Network Specialist",
  "Network Operator",
  "New Product Manager",
  "Novelist",
  "Nuclear Engineer",
  "Nuclear Specialist",
  "Nutritionist",
  "Nursing Administrator",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Operations Manager",
  "Operations Research Director",
  "Optical Technician",
  "Optometrist",
  "Organizational Development Manager",
  "Outplacement Specialist",
  "Paralegal",
  "Park Ranger",
  "Patent Attorney",
  "Payroll Specialist",
  "Personnel Specialist",
  "Petroleum Engineer",
  "Pharmacist",
  "Photographer",
  "Physical Therapist",
  "Physician",
  "Physician Assistant",
  "Physicist",
  "Planning Director",
  "Podiatrist",
  "Political Analyst",
  "Political Scientist",
  "Politician",
  "Portfolio Manager",
  "Preschool Management",
  "Preschool Teacher",
  "Principal",
  "Private Banker",
  "Private Investigator",
  "Probation Officer",
  "Process Engineer",
  "Producer",
  "Product Manager",
  "Product Engineer",
  "Production Engineer",
  "Production Planner",
  "Professional Athlete",
  "Professional Coach",
  "Professor",
  "Project Engineer",
  "Project Manager",
  "Program Manager",
  "Property Manager",
  "Public Administrator",
  "Public Safety Director",
  "PR Specialist",
  "Publisher",
  "Purchasing Agent",
  "Publishing Director",
  "Quality Assurance Specialist",
  "Quality Control Engineer",
  "Quality Control Inspector",
  "Radiology Manager",
  "Railroad Engineer",
  "Real Estate Broker",
  "Recreational Director",
  "Recruiter",
  "Redevelopment Specialist",
  "Regulatory Affairs Manager",
  "Registered Nurse",
  "Rehabilitation Counselor",
  "Relocation Manager",
  "Reporter",
  "Research Specialist",
  "Restaurant Manager",
  "Retail Store Manager",
  "Risk Analyst",
  "Safety Engineer",
  "Sales Engineer",
  "Sales Trainer",
  "Sales Promotion Manager",
  "Sales Representative",
  "Sales Manager",
  "Service Manager",
  "Sanitation Engineer",
  "Scientific Programmer",
  "Scientific Writer",
  "Securities Analyst",
  "Security Consultant",
  "Security Director",
  "Seminar Presenter",
  "Ship's Officer",
  "Singer",
  "Social Director",
  "Social Program Planner",
  "Social Research",
  "Social Scientist",
  "Social Worker",
  "Sociologist",
  "Software Developer",
  "Software Engineer",
  "Software Test Engineer",
  "Soil Scientist",
  "Special Events Manager",
  "Special Education Teacher",
  "Special Projects Director",
  "Speech Pathologist",
  "Speech Writer",
  "Sports Event Manager",
  "Statistician",
  "Store Manager",
  "Strategic Alliance Director",
  "Strategic Planning Director",
  "Stress Reduction Specialist",
  "Stockbroker",
  "Surveyor",
  "Structural Engineer",
  "Superintendent",
  "Supply Chain Director",
  "System Engineer",
  "Systems Analyst",
  "Systems Programmer",
  "System Administrator",
  "Tax Specialist",
  "Teacher",
  "Technical Support Specialist",
  "Technical Illustrator",
  "Technical Writer",
  "Technology Director",
  "Telecom Analyst",
  "Telemarketer",
  "Theatrical Director",
  "Title Examiner",
  "Tour Escort",
  "Tour Guide Director",
  "Traffic Manager",
  "Trainer Translator",
  "Transportation Manager",
  "Travel Agent",
  "Treasurer",
  "TV Programmer",
  "Underwriter",
  "Union Representative",
  "University Administrator",
  "University Dean",
  "Urban Planner",
  "Veterinarian",
  "Vendor Relations Director",
  "Viticulturist",
  "Warehouse Manager"
];


export const uuidToName = uuidString => {
  const index = uuidString.split('').reduce((sofar, letter) => letter.charCodeAt(0) + sofar, 0);
  return `${prefixes[index % prefixes.length]} ${suffixes[index % suffixes.length]}`;
}
