export const ActionTypes = {
  FETCH_BROWSER_SUMMARY: 'FETCH_BROWSER_SUMMARY',
  FETCH_BROWSER_SUMMARY_PENDING: 'FETCH_BROWSER_SUMMARY_PENDING',
  FETCH_BROWSER_SUMMARY_FAILED: 'FETCH_BROWSER_SUMMARY_FAILED',
  FETCH_BROWSER_SUMMARY_SUCCESS: 'FETCH_BROWSER_SUMMARY_SUCCESS',
};
