export const ActionTypes = {
  FETCH_BROWSER_MINUTE_SUMMARY: 'FETCH_BROWSER_MINUTE_SUMMARY',
  FETCH_BROWSER_MINUTE_SUMMARY_PENDING: 'FETCH_BROWSER_MINUTE_SUMMARY_PENDING',
  FETCH_BROWSER_MINUTE_SUMMARY_FAILED: 'FETCH_BROWSER_MINUTE_SUMMARY_FAILED',
  FETCH_BROWSER_MINUTE_SUMMARY_SUCCESS: 'FETCH_BROWSER_MINUTE_SUMMARY_SUCCESS',
};
