export const ActionTypes = {
  FETCH_BROWSER_SUMMARY: 'FETCH_BROWSER_SUMMARY',
  FETCH_BROWSER_SUMMARY_PENDING: 'FETCH_BROWSER_SUMMARY_PENDING',
  FETCH_BROWSER_SUMMARY_FAILED: 'FETCH_BROWSER_SUMMARY_FAILED',
  FETCH_BROWSER_SUMMARY_SUCCESS: 'FETCH_BROWSER_SUMMARY_SUCCESS',

  FETCH_AJAX_SUMMARY: 'FETCH_AJAX_SUMMARY',
  FETCH_AJAX_SUMMARY_PENDING: 'FETCH_AJAX_SUMMARY_PENDING',
  FETCH_AJAX_SUMMARY_SUCCESS: 'FETCH_AJAX_SUMMARY_SUCCESS',
  FETCH_AJAX_SUMMARY_FAILED: 'FETCH_AJAX_SUMMARY_FAILED',

  FETCH_AJAX_POINTS_PENDING: 'FETCH_AJAX_POINTS_PENDING',
  FETCH_AJAX_POINTS_SUCCESS: 'FETCH_AJAX_POINTS_SUCCESS',
  FETCH_AJAX_POINTS_FAILED: 'FETCH_AJAX_POINTS_FAILED',

  FETCH_PAGE_LOADS_SUMMARY: 'FETCH_PAGE_LOADS_SUMMARY',
  FETCH_PAGE_LOADS_SUMMARY_PENDING: 'FETCH_PAGE_LOADS_SUMMARY_PENDING',
  FETCH_PAGE_LOADS_SUMMARY_FAILED: 'FETCH_PAGE_LOADS_SUMMARY_FAILED',
  FETCH_PAGE_LOADS_SUMMARY_SUCCESS: 'FETCH_PAGE_LOADS_SUMMARY_SUCCESS',
};
